name: Android Release to Play Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Decode Keystore
        working-directory: ./android
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > app/keystore.jks

      - name: Create key.properties
        working-directory: ./android
        run: |
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" > key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> key.properties
          echo "storeFile=../app/keystore.jks" >> key.properties

      - name: Create Google Play Service Account JSON
        working-directory: ./android
        run: |
          echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}" > store_credentials.json 

      - name: Install dependencies
        run: flutter pub get

      - name: Build app bundle
        run: |
          flutter build appbundle --release

      - name: Upload generated aab to the artifacts
        uses: actions/upload-artifact@master
        with:
          name: aab-stores
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: store_credentials.json
          packageName: com.ohms.tictactoe
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          tracks: alpha,beta
